typography_spectrum: 0.19727256032638252
color:
  brandStrength: 0.700991784920916
  lightness: 0.8817893010564148
  saturation: 0.5943346868734807
  rhythmicContrast: 0.009492704644799232
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
opengraph:
  appId: www.facebook.com/carstoysmovies
layout_spectrum: 0.006446950603276491
name: CarsToysMovies
title: Disney Movies
