layout_spectrum: 0.9252491386141628
typography_spectrum: 0.31315142079256475
color:
  saturation: 0.24745556339621544
  brandStrength: 0.18442715937271714
  rhythmicContrast: 0.5935294891241938
  brandColors:
    - '#CC291A'
    - '#000100'
    - '#FD7119'
    - '#FEDE00'
    - '#ECE0E2'
  lightness: 0.13774014776572585
opengraph:
  appId: www.facebook.com/carstoysmovies
analytics:
  google: '54801532'
  facebook: >-
    // ViewContent // Track key page views (ex: product page, landing page or
    article) fbq('track', 'ViewContent');  // Search // Track searches on your
    website (ex. product searches) fbq('track', 'Search');  // AddToCart //
    Track when items are added to a shopping cart (ex. click/landing page on Add
    to Cart button) fbq('track', 'AddToCart');  // AddToWishlist // Track when
    items are added to a wishlist (ex. click/landing page on Add to Wishlist
    button) fbq('track', 'AddToWishlist');  // InitiateCheckout // Track when
    people enter the checkout flow (ex. click/landing page on checkout button)
    fbq('track', 'InitiateCheckout');  // AddPaymentInfo // Track when payment
    information is added in the checkout flow (ex. click/landing page on billing
    info) fbq('track', 'AddPaymentInfo');  // Purchase // Track purchases or
    checkout flow completions (ex. landing on "Thank You" or confirmation page)
    fbq('track', 'Purchase', {value: '1.00', currency: 'USD'});  // Lead //
    Track when a user expresses interest in your offering (ex. form submission,
    sign up for trial, landing on pricing page) fbq('track', 'Lead');  //
    CompleteRegistration // Track when a registration form is completed (ex.
    complete subscription, sign up for a service) fbq('track',
    'CompleteRegistration');  // Other //  fbq('track', 'Other');
name: CarsToysMovies
navigation:
  - name: CarsToysMovies
    id: da1e6fbd-64e1-4b30-a76d-c656d4cdd46a
    type: content
  - name: YouTube
    url: www.youtube.com/carstoysmovies
    type: external
  - name: Facebook
    url: 'https://www.facebook.com/carstoysmovies/'
    type: external
  - name: Twitter
    url: 'https://twitter.com/CarsToysMovies'
    type: external
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: CarsToysMovies
description: '"where cars come alive"'
