typography_spectrum: 0.19727256032638252
color:
  brandStrength: 0.700991784920916
  lightness: 0.8817893010564148
  saturation: 0.5943346868734807
  rhythmicContrast: 0.009492704644799232
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
opengraph:
  appId: www.facebook.com/carstoysmovies
layout_spectrum: 0.006446950603276491
analytics:
  google: '54801532'
  facebook: >-
    // ViewContent // Track key page views (ex: product page, landing page or
    article) fbq('track', 'ViewContent');  // Search // Track searches on your
    website (ex. product searches) fbq('track', 'Search');  // AddToCart //
    Track when items are added to a shopping cart (ex. click/landing page on Add
    to Cart button) fbq('track', 'AddToCart');  // AddToWishlist // Track when
    items are added to a wishlist (ex. click/landing page on Add to Wishlist
    button) fbq('track', 'AddToWishlist');  // InitiateCheckout // Track when
    people enter the checkout flow (ex. click/landing page on checkout button)
    fbq('track', 'InitiateCheckout');  // AddPaymentInfo // Track when payment
    information is added in the checkout flow (ex. click/landing page on billing
    info) fbq('track', 'AddPaymentInfo');  // Purchase // Track purchases or
    checkout flow completions (ex. landing on "Thank You" or confirmation page)
    fbq('track', 'Purchase', {value: '1.00', currency: 'USD'});  // Lead //
    Track when a user expresses interest in your offering (ex. form submission,
    sign up for trial, landing on pricing page) fbq('track', 'Lead');  //
    CompleteRegistration // Track when a registration form is completed (ex.
    complete subscription, sign up for a service) fbq('track',
    'CompleteRegistration');  // Other //  fbq('track', 'Other');
name: CarsToysMovies
navigation:
  - name: Cars Toys Movies
    id: da1e6fbd-64e1-4b30-a76d-c656d4cdd46a
    type: content
  - name: Our YouTube Page
    url: www.youtube.com/carstoysmovies
    type: external
title: Disney Shorts
