layout_spectrum: 0.7951524306554347
typography_spectrum: 0.8056592121720314
color:
  brandStrength: 0.06669136672280729
  lightness: 0.47842850163578987
  saturation: 0.004377233562991023
  rhythmicContrast: 0.8147937166504562
  brandColors:
    - '#CC291A'
    - '#000100'
    - '#FD7119'
    - '#FEDE00'
    - '#ECE0E2'
opengraph:
  appId: www.facebook.com/carstoysmovies
analytics:
  google: '54801532'
  facebook: >-
    // ViewContent // Track key page views (ex: product page, landing page or
    article) fbq('track', 'ViewContent');  // Search // Track searches on your
    website (ex. product searches) fbq('track', 'Search');  // AddToCart //
    Track when items are added to a shopping cart (ex. click/landing page on Add
    to Cart button) fbq('track', 'AddToCart');  // AddToWishlist // Track when
    items are added to a wishlist (ex. click/landing page on Add to Wishlist
    button) fbq('track', 'AddToWishlist');  // InitiateCheckout // Track when
    people enter the checkout flow (ex. click/landing page on checkout button)
    fbq('track', 'InitiateCheckout');  // AddPaymentInfo // Track when payment
    information is added in the checkout flow (ex. click/landing page on billing
    info) fbq('track', 'AddPaymentInfo');  // Purchase // Track purchases or
    checkout flow completions (ex. landing on "Thank You" or confirmation page)
    fbq('track', 'Purchase', {value: '1.00', currency: 'USD'});  // Lead //
    Track when a user expresses interest in your offering (ex. form submission,
    sign up for trial, landing on pricing page) fbq('track', 'Lead');  //
    CompleteRegistration // Track when a registration form is completed (ex.
    complete subscription, sign up for a service) fbq('track',
    'CompleteRegistration');  // Other //  fbq('track', 'Other');
name: CarsToysMovies
navigation:
  - name: CarsToysMovies
    id: da1e6fbd-64e1-4b30-a76d-c656d4cdd46a
    type: content
  - name: YouTube
    url: www.youtube.com/carstoysmovies
    type: external
  - name: Facebook
    url: 'https://www.facebook.com/carstoysmovies/'
    type: external
  - name: Twitter
    url: 'https://twitter.com/CarsToysMovies'
    type: external
  - name: >-
      DISNEY-LEGO Cars Toys Movies | Lightning McQueen Mack Mater | Spiderman
      Batman Joker
    id: 69f5acb4-e10c-46ec-8497-3fc259e2243c
    type: content
title: ANIMATED CARTOONS
